apiVersion: v1
kind: Service
metadata:
  name: {{ include "noteworthy-chart.fullname" . }}
  labels:
    {{- include "noteworthy-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: nextjs-app
spec:
  type: {{ .Values.nextjsApp.service.type }}
  ports:
    - name: "{{ .Values.nextjsApp.service.port }}"
      port: {{ .Values.nextjsApp.service.port }}
      targetPort: {{ .Values.nextjsApp.service.port }}
      protocol: TCP
      {{- if .Values.nextjsApp.service.nodePort }}
      nodePort: {{ .Values.nextjsApp.service.nodePort }}
      {{- end }}
  selector:
    {{- include "noteworthy-chart.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: nextjs-app