apiVersion: v1
kind: Service
metadata:
  name: {{ include "noteworthy-chart.fullname" . }}-postgres
  labels:
    {{- include "noteworthy-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  type: ClusterIP
  ports:
    - name: "{{ .Values.postgres.service.port }}"
      port: {{ .Values.postgres.service.port }}
      targetPort: {{ .Values.postgres.service.port }}
      protocol: TCP
  selector:
    {{- include "noteworthy-chart.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgres