---
apiVersion: v1
kind: Secret
metadata:
  name: { { .Values.postgres.dbCredentialsSecretName } }
  labels: { { - include "noteworthy-chart.labels" . | nindent 4 } }
type: Opaque
data:
  POSTGRES_USER:
    { { .Values.secretData.dbCredentials.POSTGRES_USER | b64enc | quote } }
  POSTGRES_PASSWORD:
    { { .Values.secretData.dbCredentials.POSTGRES_PASSWORD | b64enc | quote } }

---
apiVersion: v1
kind: Secret
metadata:
  name: { { .Values.nextjsApp.secretsName } }
  labels: { { - include "noteworthy-chart.labels" . | nindent 4 } }
type: Opaque
data:
  JWT_SECRET:
    { { .Values.secretData.nextjsAppSecrets.JWT_SECRET | b64enc | quote } }
  REFRESH_TOKEN_SECRET:
    {
      {
        .Values.secretData.nextjsAppSecrets.REFRESH_TOKEN_SECRET | b64enc | quote,
      },
    }
  APP_ENCRYPTION_KEY:
    {
      {
        .Values.secretData.nextjsAppSecrets.APP_ENCRYPTION_KEY | b64enc | quote,
      },
    }
